<a href="https://colab.research.google.com/github/kra268/ChemCoder/blob/main/backprop_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.randn(2, requires_grad=True)      # requires_grad will remember the gradient of all tensors who's PARENT is x
x

tensor([ 0.5213, -0.6427], requires_grad=True)

In [3]:
w = torch.tensor([1.0, 0.1], requires_grad=True)
w

tensor([1.0000, 0.1000], requires_grad=True)

In [4]:
y = x*w + 3       # Usually an activation function

In [5]:
y

tensor([3.5213, 2.9357], grad_fn=<AddBackward0>)

In [6]:
y_act = 5       # Assume this to be actual/true value of y

In [7]:
loss = (y_act - y).mean()     # also known as error/ loss_function or loss_fn
loss

tensor(1.7715, grad_fn=<MeanBackward0>)

In [8]:
loss.backward()     # backpropagates the loss/error

In [9]:
x.grad

tensor([-0.5000, -0.0500])

In [10]:
for epoch in range(3):
  y = x*w + 3
  loss = (y_act - y).mean()# This would usually be the loss function
  loss.backward()
  print(x.grad)

tensor([-1.0000, -0.1000])
tensor([-1.5000, -0.1500])
tensor([-2.0000, -0.2000])


In [11]:
x.grad.zero_()

tensor([0., 0.])

In [12]:
for epoch in range(3):
  y = x*w + 3
  loss = (y_act - y).mean()# This would usually be the loss function
  loss.backward()
  print(x.grad)
  x.grad.zero_()        # Make the gradients '0' before the next iteration

tensor([-0.5000, -0.0500])
tensor([-0.5000, -0.0500])
tensor([-0.5000, -0.0500])


In [13]:
w

tensor([1.0000, 0.1000], requires_grad=True)

In [14]:
# Update the weights using an optimizer.
# There are many types but more on that later.
optimizer = torch.optim.Adam([w], lr=0.01)

In [15]:
for epoch in range(3):
  y = x*w + 3
  loss = (y_act - y).mean()# This would usually be the loss function
  loss.backward()
  optimizer.step()        # This updates the parameters based on the gradient
  print(f'this is gradient of x {x.grad}')
  print(f'this is w {w}')
  x.grad.zero_()

this is gradient of x tensor([-0.5000, -0.0500])
this is w tensor([1.0100, 0.0900], requires_grad=True)
this is gradient of x tensor([-0.5050, -0.0450])
this is w tensor([1.0200, 0.0800], requires_grad=True)
this is gradient of x tensor([-0.5100, -0.0400])
this is w tensor([1.0300, 0.0700], requires_grad=True)
