<a href="https://colab.research.google.com/github/kra268/ChemCoder/blob/main/torch_tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
# Initialization

data = [[1,2,3],[4,5,6]]
tensor = torch.Tensor(data)

In [3]:
data

[[1, 2, 3], [4, 5, 6]]

In [4]:
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [5]:
tensor.add(1)

tensor([[2., 3., 4.],
        [5., 6., 7.]])

In [6]:
tensor.add(tensor)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [7]:
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
n = np.array(data)
n

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
n_t = torch.from_numpy(n)

In [10]:
n_t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
n_a = np.array(n_t)

In [12]:
n_a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
x_rand = torch.rand(2,3)
x_rand

tensor([[0.1888, 0.5427, 0.5913],
        [0.1598, 0.8512, 0.3606]])

In [16]:
x_ones = torch.ones(2,3)
x_ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
shape = (2,3,)

In [18]:
x_zeros = torch.zeros(shape)

In [19]:
x_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
x_zeros.shape

torch.Size([2, 3])

In [21]:
x_zeros.dtype

torch.float32

In [22]:
x_zeros.device

device(type='cpu')

In [26]:
if torch.cuda.is_available():
  x_zeros = x_zeros.to('cuda')

In [27]:
x_zeros.device

device(type='cuda', index=0)

In [28]:
# stack and cat

In [29]:
x1 = torch.rand(shape)
x2 = torch.rand(shape)

In [30]:
print(x1)
print(x2)

tensor([[0.1987, 0.8236, 0.8483],
        [0.9995, 0.0079, 0.8386]])
tensor([[0.7301, 0.0925, 0.4030],
        [0.9700, 0.3081, 0.0416]])


In [32]:
torch.stack([x1,x2])

tensor([[[0.1987, 0.8236, 0.8483],
         [0.9995, 0.0079, 0.8386]],

        [[0.7301, 0.0925, 0.4030],
         [0.9700, 0.3081, 0.0416]]])

In [33]:
torch.cat([x1,x2])

tensor([[0.1987, 0.8236, 0.8483],
        [0.9995, 0.0079, 0.8386],
        [0.7301, 0.0925, 0.4030],
        [0.9700, 0.3081, 0.0416]])

In [34]:
# original tensor
'''tensor([[0.1987, 0.8236, 0.8483],
        [0.9995, 0.0079, 0.8386]])'''

'tensor([[0.1987, 0.8236, 0.8483],\n        [0.9995, 0.0079, 0.8386]])'

In [35]:
# stacking
'''tensor([[[0.1987, 0.8236, 0.8483],
         [0.9995, 0.0079, 0.8386]],

        [[0.7301, 0.0925, 0.4030],
         [0.9700, 0.3081, 0.0416]]])'''

'tensor([[[0.1987, 0.8236, 0.8483],\n         [0.9995, 0.0079, 0.8386]],\n\n        [[0.7301, 0.0925, 0.4030],\n         [0.9700, 0.3081, 0.0416]]])'

In [36]:
# concatanation
'''tensor([[0.1987, 0.8236, 0.8483],
        [0.9995, 0.0079, 0.8386],
        [0.7301, 0.0925, 0.4030],
        [0.9700, 0.3081, 0.0416]])'''

'tensor([[0.1987, 0.8236, 0.8483],\n        [0.9995, 0.0079, 0.8386],\n        [0.7301, 0.0925, 0.4030],\n        [0.9700, 0.3081, 0.0416]])'

In [37]:
mat1 = torch.ones(3,3)
mat2 = torch.ones(3,3)

In [38]:
mat1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [39]:
mat1@mat2

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [40]:
torch.matmul(mat1,mat2)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [41]:
mat1.matmul(mat2)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [42]:
y = torch.rand_like(mat1)
y

tensor([[0.6945, 0.3944, 0.3727],
        [0.4179, 0.4978, 0.3627],
        [0.6100, 0.3400, 0.6415]])

In [43]:
torch.matmul(mat1,mat2, out=y)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [44]:
y

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [45]:
torch.mul(mat1,mat2)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [46]:
torch.mul(mat1,mat2, out=y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [47]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [48]:
g = y.sum()
g

tensor(9.)

In [49]:
g_item = g.item()

In [50]:
g_item

9.0

In [51]:
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [52]:
y.add_(1)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [53]:
y

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [54]:
x_ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [56]:
x_ones.add_(1)
x_ones

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [58]:
x_ones.copy_(x_zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [59]:
x_ones

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [60]:
# Bridging between tensors and numpy

In [61]:
a = torch.ones(2,2)

In [62]:
b = a.numpy()
b

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [63]:
a.add_(1)

tensor([[2., 2.],
        [2., 2.]])

In [64]:
b

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [66]:
a = np.ones([3,3])
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
b = torch.from_numpy(a)

In [68]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [70]:
np.add(a, 1, out=a)
a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [71]:
b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)